application: factomexplorer
version:     factomexplorer-2015-09-09
runtime:     go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  secure: always
- url: /Admin
  script: _go_app
  secure: always
  login: admin