application: factomexplorer
#application: factomtestnetexplorer
version:     factomexplorer-2015-10-19-2
runtime:     go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /scss
  static_dir: scss
- url: /.*
  script: _go_app
  secure: optional
- url: /Admin
  script: _go_app
  secure: always
  login: admin
